name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    environment:
      name: Release
    permissions:
      id-token: write
      contents: write  # <-- Add this line to allow pushing tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install tox

      - name: Run tests
        run: poetry run tox

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        run: |
          if git rev-parse "v${{ steps.get_version.outputs.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.get_version.outputs.VERSION }} already exists. Skipping release."
            exit 0
          fi

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag "v${{ steps.get_version.outputs.VERSION }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin "v${{ steps.get_version.outputs.VERSION }}"